### ISSUE TITLE
library(clpb): Unexpected domain error

### ISSUE THREAD

**Issue by triska** [trealla-prolog/trealla#360]
To reproduce this issue, please save the following example program as `testing.pl`:

<pre>
:- use_module(library(clpb)).

permutation([], []).
permutation(List, [First|Perm]) :-
        select(First, List, Rest),
        permutation(Rest, Perm).

sat(_)  --&gt; [].
sat(X*Y) --&gt; [_], sat(X), sat(Y).
sat(X+Y) --&gt; [_], sat(X), sat(Y).
sat(X#Y) --&gt; [_], sat(X), sat(Y).
sat(card([0,1],[X,Y])) --&gt; [_], sat(X), sat(Y).

vs_eqs(Vs, Eqs) :- phrase(vs_eqs(Vs), Eqs).

vs_eqs([]) --&gt; [].
vs_eqs([V|Vs]) --&gt; vs_eqs_(Vs, V), vs_eqs(Vs).

vs_eqs_([], _) --&gt; [].
vs_eqs_([V|Vs], X) --&gt; vs_eqs_(Vs, X), ( [X=V] ; [] ).

run(N) :-
        length(Ls, N),
        portray_clause(N),
        phrase(sat(Sat1), Ls),
        phrase(sat(Sat2), Ls),
        term_variables(Sat1-Sat2, Vs0),
        permutation(Vs0, Vs),
        vs_eqs(Vs, Eqs),
        findall(Vs, (sat(Sat1),sat(Sat2),maplist(call, Eqs),labeling(Vs)), Sols1),
        findall(Vs, (labeling(Vs),maplist(call,Eqs),sat(Sat1*Sat2)), Sols2),
        (   sort(Sols1, Sols), sort(Sols2, Sols) -&gt; true
        ;   throw(neq-Sat1-Sat2-Eqs-Vs0-Vs-Sols1-Sols2)
        ),
        false.

run :- run(_).
</pre>

And then do:

<pre>
<b>$ ./tpl -O0 testing.pl</b>
Trealla Prolog (c) Infradig 2020-2023, v2.29.3
<b>?- run.</b>
0.
1.
   error(domain_error(clpb_variable,[_23,[_23,[_23|_24],_25],_25]),unknown([_23,[_23|_24],_25])-1), unexpected.
</pre>

**Comment by triska** [comment]
Very nice, thank you a lot! Let's continue with #366.

**Comment by infradig** [comment]
Was fixed due to a typo, so not really. Re-opening this.

**Comment by triska** [comment]
I now no longer get a domain error, so the specific instance of this issue seems resolved.

However, a different issue remains:

<pre>
?- run.
0.
1.
   neq-_23*_24-(_25+_26)-[_23=_24,_25=_26]-[_23,_24,_25,_26]-[_23,_24,_25,_26]-[]-[[1,1,1,1]].
</pre>

#369 may be a shorter example of this issue.

**Comment by jgarte** [comment]
Hi, should this particular issue be closed?

**Comment by infradig** [comment]
No, maybe one day the mystery of CLPB will be resolved.

**Comment by infradig** [comment]
Fixed:
```
➜  trealla git:(main) ✗ tpl perm.pl
Trealla Prolog (c) Infradig 2020, v2.100.13-1-g6fa7-dirty
?- run.
0.
1.
2.
^C
Action or (h)elp: e

➜  trealla git:(main) ✗ scryer-prolog perm.pl
?- run.
0.
1.
2.
^C   error('$interrupt_thrown',repl/0).
?-
➜  trealla git:(main) ✗
```

**Comment by triska** [comment]
Surely 86c8f24c768922d331b72003f2274ac85d6334f9 cannot be considered a fix no? It's putting the problem under the rug, needlessly making it harder to find. We can be glad that this time, we have such an easy way to produce the problem.

**Comment by infradig** [comment]
No it's not, but for now it will do. Don't close the issues.

**Comment by infradig** [comment]
Oh, and it localises the problem definition.

**Comment by infradig** [comment]
Well whaddaya know, just noticed it isn't even needed anymore.

**Comment by infradig** [comment]
Fixed.

**Comment by triska** [comment]
Awesome, thank you a lot!
